### ISSUE TITLE
Issues about bioinformatics-snakemake-pipelines/genome-ani-leiden-clustering-pipeline

### ISSUE THREAD

**Issue by xjhzjucas** [apcamargo/bioinformatics-snakemake-pipelines#1]
Hi Dr.Camargo:
I find this nice project when I read your IMG/VR v4 manuscripts published on Nucleic Acids Research. I have some doubts about this and hope you can help me about them. 
1.I tried this project using the command like this:
**nohup snakemake --config input=virus30_aftercheckv.fna.split output=representative_genomes_directory leiden_resolution=1.0 avg_ani=0.95 min_ani=0.0 min_cov=0.85 blast_threads=16 --cores 16 -s genome-ani-leiden-clustering-pipeline.smk &**

and it turned error like this:
[Tue Feb 20 21:55:34 2024]
rule anicalc:
    input: virus30_aftercheckv.fna.split_concatenated.fna, virus30_aftercheckv.fna.split_blast_sorted.tsv
    output: virus30_aftercheckv.fna.split_ani.tsv
    jobid: 4

Removing temporary output file virus30_aftercheckv.fna.split_blast_sorted.tsv.
[Tue Feb 20 22:00:01 2024]
Finished job 4.
6 of 9 steps (67%) done

[Tue Feb 20 22:00:01 2024]
rule aniclust:
    input: virus30_aftercheckv.fna.split_concatenated.fna, virus30_aftercheckv.fna.split_ani.tsv
    output: virus30_aftercheckv.fna.split_clusters.tsv
    jobid: 2

Traceback (most recent call last):
  File "/mnt/sdb/xjh/proj_vlp_bulk/bulk_assembly_genomad/votu30_after_checkv/.snakemake/scripts/tmps86bt2ol.aniclust.py", line 64, in <module>
    min_ani=snakemake.params.min_ani,
AttributeError: 'Params' object has no attribute 'min_ani'
[Tue Feb 20 22:00:01 2024]
Error in rule aniclust:
    jobid: 2
    output: virus30_aftercheckv.fna.split_clusters.tsv

RuleException:
CalledProcessError in line 65 of /mnt/sdb/xjh/proj_vlp_bulk/bulk_assembly_genomad/votu30_after_checkv/genome-ani-leiden-clustering-pipeline.smk:
Command 'set -euo pipefail;  /mnt/sdb/xjh/miniconda3/envs/suv_threesoft/bin/python3.10 /mnt/sdb/xjh/proj_vlp_bulk/bulk_assembly_genomad/votu30_after_checkv/.snakemake/scripts/tmps86bt2ol.aniclust.py' returned non-zero exit status 1.
  File "/mnt/sdb/xjh/miniconda3/envs/suv_threesoft/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2208, in run_wrapper
  File "/mnt/sdb/xjh/proj_vlp_bulk/bulk_assembly_genomad/votu30_after_checkv/genome-ani-leiden-clustering-pipeline.smk", line 65, in __rule_aniclust
  File "/mnt/sdb/xjh/miniconda3/envs/suv_threesoft/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/mnt/sdb/xjh/miniconda3/envs/suv_threesoft/lib/python3.10/concurrent/futures/thread.py", line 52, in run
  File "/mnt/sdb/xjh/miniconda3/envs/suv_threesoft/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/mnt/sdb/xjh/miniconda3/envs/suv_threesoft/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2239, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/sdb/xjh/proj_vlp_bulk/bulk_assembly_genomad/votu30_after_checkv/.snakemake/log/2024-02-20T211837.878935.snakemake.log
I don't know what's wrong about this.

2.In your IMG/VR v4 manuscript published on Nucleic Acids Research I saw other 2 steps (i.e. BLAST and ANI AF compute) before Leiden algorithm when clustering viral contigs into vOTUs. Can I only use the Leiden algorithm(https://github.com/apcamargo/ bioinformatics-snakemake-pipelines/tree/main/genomeani-leiden-clustering-pipeline) to cluster viral contigs into vOTUs? I am not very clear what's the functions of the BLAST and ANI AF computation.

3.If I have several samples of viral contigs (like sample1 sample2 sample3......), when I finish using this Leiden algorithm to cluster vOTUS among all samples, is it possible to know which samples does the specific vOTU exits? Which way is more recommended below: 
a.Cluster vOTUs among all samples of the study.
b.Cluster vOTUs in each samples separately.

I am sorry to ask such basic questions due to my limited knowledge。
Thank you very much for your time!
Best wishes

**Comment by apcamargo** [comment]
Just so I understand. Each genome here is in a file within `virus30_aftercheckv.fna.split`? If so, are those genomes comprised of a single contigs or each genome may have multiple contig (e.g. viral MAGs)? Since it seems you used `seqkit` to split the sequences into multiple files, I assume that you want to cluster single-contig genomes. In this case, you should use the [`contig-ani-leiden-clustering-pipeline`](https://github.com/apcamargo/bioinformatics-snakemake-pipelines/tree/main/contig-ani-leiden-clustering-pipeline), which takes as input a single FASTA file where each sequence is a genome (in your case, a virus genome).

> 2.In your IMG/VR v4 manuscript published on Nucleic Acids Research I saw other 2 steps (i.e. BLAST and ANI AF compute) before Leiden algorithm when clustering viral contigs into vOTUs. Can I only use the Leiden algorithm([@apcamargo](https://github.com/apcamargo/) bioinformatics-snakemake-pipelines/tree/main/genomeani-leiden-clustering-pipeline) to cluster viral contigs into vOTUs? I am not very clear what's the functions of the BLAST and ANI AF computation.

The BLAST searches and ANI computation serve to create a graph connecting viruses that are very similar (high ANI and high AF). The Leiden algorithm then takes this graph and find clusters of viruses that are highly interconnected.

If you computed genomic similarity using an alternative method, you can still cluster the genomes using Leiden though [`pyleiden`](https://github.com/apcamargo/pyleiden).

> 3.If I have several samples of viral contigs (like sample1 sample2 sample3......), when I finish using this Leiden algorithm to cluster vOTUS among all samples, is it possible to know which samples does the specific vOTU exits? Which way is more recommended below:
a.Cluster vOTUs among all samples of the study.
b.Cluster vOTUs in each samples separately.

I'd cluster them all together, but you need to have a way to track from which sample each virus came from. You could just add this information to the header of the sequences.

**Comment by xjhzjucas** [comment]
Hi Dr.Camargo: thank you for helping me. 
About the 2nd question, can I consider this genome-ani-leiden-clustering-pipeline serves as the same function as another scripts in checkv project?(i.e. https://bitbucket.org/berkeleylab/checkv/src/master/scripts/aniclust.py) as they are both run after the script (https://bitbucket.org/berkeleylab/checkv/src/master/scripts/anicalc.py)

**Comment by apcamargo** [comment]
Yes. That pipeline will run `anicalc` and then cluster with the Leiden algorithm.

**Comment by xjhzjucas** [comment]
OK I understand, thank you for your help!

**Comment by mujiezhang** [comment]
> Yes. That pipeline will run `anicalc` and then cluster with the Leiden algorithm.

Are there any difference between your pipeline and the checkv ani cluster method?

**Comment by apcamargo** [comment]
No. The clustering algorithm is the same.

**Comment by xjhzjucas** [comment]
> > Yes. That pipeline will run `anicalc` and then cluster with the Leiden algorithm.
> 
> Are there any difference between your pipeline and the checkv ani cluster method?

Hi mujie师兄,我拜读过蹇老师实验室的几篇佳作，不知道能否加您一个联系方式呀

**Comment by mujiezhang** [comment]
> No. The clustering algorithm is the same.

Thanks

**Comment by mujiezhang** [comment]
> > > Yes. That pipeline will run `anicalc` and then cluster with the Leiden algorithm.
> > 
> > 
> > Are there any difference between your pipeline and the checkv ani cluster method?
> 
> Hi mujie师兄,我拜读过蹇老师实验室的几篇佳作，不知道能否加您一个联系方式呀

可以的，zhangmujie@sjtu.edu.cn
